version: '3'

services:
  service:
    image: qutiian14/tybatest:1.0.0
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: postgres
      DB_PORT: '5432'
      DB_NAME: 'test'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_MAX_POOL_SIZE: 10
      SOCKET_TIME_OUT: 50
      TIMEZONE: 'America/Bogota'
    command: >
      ./gradlew --no-daemon
      -g ./.gradle-cache
      --info --stacktrace
      test jacocoTestReport
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
  redis:
    image: redis:alpine